/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import Classes.ADM;
import Classes.Usuario;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author a1658948
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    private ADM adm;
    private boolean[] dadosValidos = new boolean[11];
    private final Color corValido = new Color(10, 200, 150);
    private final Color corInvalido = new Color(125, 30, 150);
    private final Color corFundo = new Color(150, 200, 255);
    private final String textoValido = "     Dado Válido";
    private final String textoInvalido = "     Dado Inválido";
    private short campoID;
    /**
     * Creates new form CadatrarUsuario
     * @param a
     */
    public CadastrarUsuario(ADM a) {
        initComponents();
        this.adm = a;
    }
    
    private CadastrarUsuario() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecionaTipoUsuario = new javax.swing.ButtonGroup();
        selecionaTipoTelefone = new javax.swing.ButtonGroup();
        painelDados = new javax.swing.JLayeredPane();
        campoCidade = new javax.swing.JTextField();
        labCidade = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labRG = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        labEndereco = new javax.swing.JLabel();
        labUF = new javax.swing.JLabel();
        labCEP = new javax.swing.JLabel();
        selecionaUF = new javax.swing.JComboBox<>();
        campoRG = new javax.swing.JFormattedTextField();
        campoNome = new javax.swing.JFormattedTextField();
        campoCEP = new javax.swing.JFormattedTextField();
        labTelefone = new javax.swing.JLabel();
        try{
            formataTelefone = new MaskFormatter("(**)*****-****");
            formataTelefone.setValidCharacters("_0123456789");
            campoTelefone = new JFormattedTextField(formataTelefone);
        } catch(Exception e){
        }
        campoTelefone = new javax.swing.JFormattedTextField();
        labTipoTelefone = new javax.swing.JLabel();
        selecionaFixo = new javax.swing.JRadioButton();
        selecionaCelular = new javax.swing.JRadioButton();
        labDataNasc = new javax.swing.JLabel();
        campoDataNasc = new javax.swing.JFormattedTextField();
        labCadastro = new javax.swing.JLabel();
        painelLogin = new javax.swing.JLayeredPane();
        labLogin = new javax.swing.JLabel();
        labSenha = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        separadorV = new javax.swing.JSeparator();
        labTipoUsuario = new javax.swing.JLabel();
        selecionaAdmin = new javax.swing.JRadioButton();
        selecionaUsuario = new javax.swing.JRadioButton();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        separadorHInt = new javax.swing.JSeparator();
        separadorHSup = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        campoCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCidadeFocusLost(evt);
            }
        });

        labCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCidade.setText("Cidade");
        labCidade.setName("Cidade"); // NOI18N

        labNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labNome.setText("Nome Completo");
        labNome.setName("Nome Completo"); // NOI18N

        labRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRG.setText("RG");
        labRG.setName("RG"); // NOI18N

        campoEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEnderecoFocusLost(evt);
            }
        });

        labEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labEndereco.setText("Endereço");
        labEndereco.setName("Endereço"); // NOI18N

        labUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUF.setText("Estado ou UF");
        labUF.setName("Estado ou UF"); // NOI18N

        labCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCEP.setText("CEP");
        labCEP.setName("CEP"); // NOI18N

        selecionaUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionaUF.setMaximumRowCount(27);
        selecionaUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "ACRE", "ALAGOAS", "AMAPÁ", "AMAZONAS", "BAHIA", "CEARÁ", "DISTRITO FEDERAL", "ESPÍRITO SANTO", "GOIÁS", "MARANHÃO", "MATO GROSSO", "MATO GROSSO DO SUL", "MINAS GERAIS", "PARÁ", "PARAÍBA", "PARANÁ", "PERNAMBUCO", "PIAUÍ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RIO GRANDE DO SUL", "RONDÔNIA", "RORAIMA", "SANTA CATARINA", "SÃO PAULO", "SERGIPE", "TOCANTINS" }));
        selecionaUF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                selecionaUFFocusLost(evt);
            }
        });

        try{
            formataRG = new MaskFormatter("**.***.***-*");
            formataRG.setValidCharacters("_0123456789");
            campoRG = new JFormattedTextField(formataRG);
        } catch(Exception e){
        }
        campoRG.setText("__.___.___-_");
        campoRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRGFocusLost(evt);
            }
        });

        campoNome.setColumns(200);
        campoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFocusLost(evt);
            }
        });

        try{
            formataCEP = new MaskFormatter("*****-***");
            formataCEP.setValidCharacters("_0123456789");
            campoCEP = new JFormattedTextField(formataCEP);
        } catch(Exception e){
        }
        campoCEP.setText("_____-___");
        campoCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCEPFocusLost(evt);
            }
        });
        campoCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCEPKeyTyped(evt);
            }
        });

        labTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTelefone.setText("Telefone");
        labTelefone.setName("Telefone"); // NOI18N

        campoTelefone.setText("(__)_____-____");
        campoTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusLost(evt);
            }
        });
        campoTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefoneKeyTyped(evt);
            }
        });

        labTipoTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTipoTelefone.setText("Tipo de Telefone");
        labTipoTelefone.setName("Telefone"); // NOI18N

        selecionaTipoTelefone.add(selecionaFixo);
        selecionaFixo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionaFixo.setSelected(true);
        selecionaFixo.setText("Fixo");

        selecionaTipoTelefone.add(selecionaCelular);
        selecionaCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionaCelular.setText("Celular");

        labDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labDataNasc.setText("Data de Nascimento");
        labDataNasc.setName("Data de Nascimento"); // NOI18N

        try{
            formataDataNasc = new MaskFormatter("**/**/****");
            formataDataNasc.setValidCharacters("_0123456789");
            campoDataNasc = new JFormattedTextField(formataDataNasc);
        } catch(Exception e){
        }
        campoDataNasc.setText("__/__/____");
        campoDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoDataNasc.setVerifyInputWhenFocusTarget(false);
        campoDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataNascFocusLost(evt);
            }
        });
        campoDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDataNascKeyTyped(evt);
            }
        });

        painelDados.setLayer(campoCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labRG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labUF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labCEP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(selecionaUF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoRG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoCEP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labTipoTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(selecionaFixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(selecionaCelular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(labDataNasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelDados.setLayer(campoDataNasc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEndereco)
                            .addComponent(labCidade)
                            .addComponent(labNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEndereco)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(campoCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addComponent(selecionaCelular)
                                        .addGap(18, 18, 18)
                                        .addComponent(selecionaFixo))
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(labTipoTelefone)))
                                .addGap(76, 76, 76)
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labTelefone)
                                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)))
                        .addGap(18, 18, 18)))
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionaUF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labUF)
                    .addComponent(labCEP)
                    .addComponent(labRG)
                    .addComponent(labDataNasc)
                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(labRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCEP)
                    .addComponent(labEndereco))
                .addGap(4, 4, 4)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCidade)
                    .addComponent(labUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionaUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTelefone)
                    .addComponent(labTipoTelefone)
                    .addComponent(labDataNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionaCelular)
                    .addComponent(selecionaFixo)
                    .addComponent(campoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labCadastro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labCadastro.setText("Cadastro de Usuário");

        labLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labLogin.setText("Login");
        labLogin.setName("Login"); // NOI18N

        labSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labSenha.setText("Senha");
        labSenha.setName("Senha"); // NOI18N

        labEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labEmail.setText("Email");
        labEmail.setName("Email"); // NOI18N

        campoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoLoginFocusLost(evt);
            }
        });

        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        separadorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTipoUsuario.setText("Tipo de Usuário");

        selecionaTipoUsuario.add(selecionaAdmin);
        selecionaAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionaAdmin.setText("Administrador");

        selecionaTipoUsuario.add(selecionaUsuario);
        selecionaUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionaUsuario.setText("Usuário");

        confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFocoGanho(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });

        painelLogin.setLayer(labLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(labSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(labEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(campoLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(campoEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(separadorV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(labTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(selecionaAdmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(selecionaUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(confirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(cancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLogin.setLayer(campoSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labLogin)
                    .addComponent(campoEmail)
                    .addComponent(labEmail)
                    .addComponent(labSenha)
                    .addComponent(campoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(campoSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labTipoUsuario)
                        .addGap(67, 67, 67))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLoginLayout.createSequentialGroup()
                                .addComponent(selecionaAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selecionaUsuario)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addComponent(labLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(labSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(labEmail)
                        .addGap(7, 7, 7)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addComponent(labTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selecionaAdmin)
                            .addComponent(selecionaUsuario))
                        .addGap(18, 18, 18)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(separadorV)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labCadastro)
                .addGap(252, 252, 252))
            .addComponent(separadorHInt)
            .addComponent(separadorHSup)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(painelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addComponent(painelLogin))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separadorHSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(separadorHInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String nome;
    private String RG;
    private String endereco;
    private String CEP;
    private String cidade;
    private String UF;
    private String telefone;
    private String dataNasc;
    private String nomeUsuario;
    private String senha;
    private String email;
    
    private void modificaRotulo(JLabel rotulo, boolean validade) {
        if(validade == true) {
            this.dadosValidos[this.campoID] = true;
            rotulo.setText(rotulo.getName() + this.textoValido);
            rotulo.setForeground(this.corValido);
        }
        
        else {
            this.dadosValidos[this.campoID] = false;
            rotulo.setText(rotulo.getName() + this.textoInvalido);
            rotulo.setForeground(this.corInvalido);
        }
    }
    
    private void campoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusLost
        this.nome = this.campoNome.getText();
        this.campoID = 0;
        this.campoNome.setBackground(Color.WHITE);
        
        if(this.nome.trim().length() > 1) {
            modificaRotulo(this.labNome, true);
        }
        
        else {
            modificaRotulo(this.labNome, false);
        }
    }//GEN-LAST:event_campoNomeFocusLost
    
    private void campoEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoFocusLost
        this.endereco = this.campoEndereco.getText();
        this.campoID = 2;
        this.campoEndereco.setBackground(Color.WHITE);
        
        if(!this.endereco.equals("")) {
            modificaRotulo(labEndereco, true);
        }
        
        else {
            modificaRotulo(labEndereco, false);
        }
    }//GEN-LAST:event_campoEnderecoFocusLost

    private void campoCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPFocusLost
        this.CEP = this.campoCEP.getText();
        this.campoID = 3;
        this.campoCEP.setBackground(Color.WHITE);
        
        if(this.CEP.trim().length() == 9) {
            modificaRotulo(labCEP, true);
        }
        
        else {
            modificaRotulo(labCEP, false);
        }
    }//GEN-LAST:event_campoCEPFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        this.adm.mostraInterface();
    }//GEN-LAST:event_formWindowClosed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if(verificaDados()) {
            Usuario u = new Usuario(0, this.nome, this.RG, this.endereco, this.CEP, this.cidade, this.UF, this.telefone, this.dataNasc, this.nomeUsuario, this.senha, this.email);
            this.dispose();
            this.adm.mostraInterface();
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
        this.adm.mostraInterface();
    }//GEN-LAST:event_cancelarActionPerformed

    private void campoRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGFocusLost
        this.RG = this.campoRG.getText();
        this.campoID = 1;
        this.campoRG.setBackground(Color.WHITE);
        
        if(!this.RG.equals("")) {
            modificaRotulo(labRG, true);
        }
        
        else {
            modificaRotulo(labRG, false);
        }
    }//GEN-LAST:event_campoRGFocusLost

    private void campoCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCidadeFocusLost
        this.cidade = this.campoCidade.getText();
        this.campoID = 4;
        this.campoCidade.setBackground(Color.WHITE);
        
        if(!this.cidade.equals("")) {
            modificaRotulo(labCidade, true);
        }
        
        else {
            modificaRotulo(labCidade, false);
        }
    }//GEN-LAST:event_campoCidadeFocusLost

    private void selecionaUFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selecionaUFFocusLost
        this.UF = this.selecionaUF.getSelectedItem().toString();
        this.campoID = 5;
        this.selecionaUF.setBackground(Color.WHITE);
        
        if(!this.UF.equals("-")) {
            modificaRotulo(labUF, true);
        }
        
        else {
            modificaRotulo(labUF, false);
        }
    }//GEN-LAST:event_selecionaUFFocusLost

    private void campoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusLost
        this.telefone = this.campoTelefone.getText();
        this.campoID = 6;
        this.campoTelefone.setBackground(Color.WHITE);
        
        if(!this.telefone.equals("")) {
            modificaRotulo(labTelefone, true);
        }
        
        else {
            modificaRotulo(labTelefone, false);
        }
    }//GEN-LAST:event_campoTelefoneFocusLost

    private void campoLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoLoginFocusLost
        this.nomeUsuario = this.campoLogin.getText();
        this.campoID = 8;
        this.campoLogin.setBackground(Color.WHITE);
        
        if(!this.nomeUsuario.equals("")) {
            modificaRotulo(labLogin, true);
        }
        
        else {
            modificaRotulo(labLogin, false);
        }
    }//GEN-LAST:event_campoLoginFocusLost

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        this.email = this.campoEmail.getText();
        this.campoID = 10;
        this.campoEmail.setBackground(Color.WHITE);
        
        if(!this.email.equals("")) {
            modificaRotulo(labEmail, true);
        }
        
        else {
            modificaRotulo(labEmail, false);
        }
    }//GEN-LAST:event_campoEmailFocusLost

    private void campoTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefoneKeyTyped
        
    }//GEN-LAST:event_campoTelefoneKeyTyped

    private void campoCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCEPKeyTyped
        if(evt.getKeyChar() == '-') {
            campoCEP.setCaretPosition(campoCEP.getCaretPosition());
        }
    }//GEN-LAST:event_campoCEPKeyTyped

    private void campoFocoGanho(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFocoGanho
        JTextComponent comp = (JTextComponent)evt.getComponent();
        comp.setBackground(corFundo);
        comp.setCaretPosition(0);
    }//GEN-LAST:event_campoFocoGanho

    private void campoDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataNascFocusLost
        this.dataNasc = this.campoDataNasc.getText();
        this.campoID = 7;
        this.campoDataNasc.setBackground(Color.WHITE);
        
        if(!this.dataNasc.equals("")) {
            modificaRotulo(labDataNasc, true);
        }
        
        else {
            modificaRotulo(labDataNasc, false);
        }
    }//GEN-LAST:event_campoDataNascFocusLost

    private void campoDataNascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDataNascKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataNascKeyTyped

    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        this.senha = Arrays.toString(this.campoSenha.getPassword());
        this.campoID = 9;
        this.campoSenha.setBackground(Color.WHITE);
        
        if(!this.senha.equals("")) {
            modificaRotulo(labSenha, true);
        }
        
        else {
            modificaRotulo(labSenha, false);
        }
    }//GEN-LAST:event_campoSenhaFocusLost
    
    private boolean verificaDados() {
        int i;
        
        for(i = 0; i < this.dadosValidos.length; i++) {
            if(this.dadosValidos[i] == false) {
                return false;
            }
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }
    
    private javax.swing.text.MaskFormatter formataCEP;
    private javax.swing.text.MaskFormatter formataRG;
    private javax.swing.text.MaskFormatter formataDataNasc;
    private javax.swing.text.MaskFormatter formataTelefone;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoCEP;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JFormattedTextField campoDataNasc;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JFormattedTextField campoNome;
    private javax.swing.JFormattedTextField campoRG;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel labCEP;
    private javax.swing.JLabel labCadastro;
    private javax.swing.JLabel labCidade;
    private javax.swing.JLabel labDataNasc;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labEndereco;
    private javax.swing.JLabel labLogin;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labRG;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JLabel labTipoTelefone;
    private javax.swing.JLabel labTipoUsuario;
    private javax.swing.JLabel labUF;
    private javax.swing.JLayeredPane painelDados;
    private javax.swing.JLayeredPane painelLogin;
    private javax.swing.JRadioButton selecionaAdmin;
    private javax.swing.JRadioButton selecionaCelular;
    private javax.swing.JRadioButton selecionaFixo;
    private javax.swing.ButtonGroup selecionaTipoTelefone;
    private javax.swing.ButtonGroup selecionaTipoUsuario;
    private javax.swing.JComboBox<String> selecionaUF;
    private javax.swing.JRadioButton selecionaUsuario;
    private javax.swing.JSeparator separadorHInt;
    private javax.swing.JSeparator separadorHSup;
    private javax.swing.JSeparator separadorV;
    // End of variables declaration//GEN-END:variables
}
