/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.ADM;
import Classes.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author a1658948
 */
public class ConsultarDados extends javax.swing.JFrame {
    private JFrame janelaAnterior;
    
    public ConsultarDados(Usuario u) {
        initComponents();
        this.janelaAnterior = u.getIntUsuario();
        this.nome.setText(u.getNome());
        this.RG.setText(u.getRG());
        this.endereco.setText(u.getRG());
        this.CEP.setText(u.getCEP());
        this.cidade.setText(u.getCidade());
        this.UF.setText(u.getUF());
        this.telefone.setText(u.getTelefone());
        this.dataNascimento.setText(u.getDataNascimento());
        this.login.setText(u.getNomeUsuario());
        this.email.setText(u.getEmail());
    }
    
    public ConsultarDados(ADM a) {
        initComponents();
        this.janelaAnterior = a.getIntAdm();
        this.nome.setText(a.getNome());
        this.RG.setText(a.getRG());
        this.endereco.setText(a.getRG());
        this.CEP.setText(a.getCEP());
        this.cidade.setText(a.getCidade());
        this.UF.setText(a.getUF());
        this.telefone.setText(a.getTelefone());
        this.dataNascimento.setText(a.getDataNascimento());
        this.login.setText(a.getNomeUsuario());
        this.email.setText(a.getEmail());
    }

    private ConsultarDados() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labRG = new javax.swing.JLabel();
        labEndereco = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labCEP = new javax.swing.JLabel();
        labUF = new javax.swing.JLabel();
        labCidade = new javax.swing.JLabel();
        labLogin = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        labCons = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        UF = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        separadorHInf = new javax.swing.JSeparator();
        telefone = new javax.swing.JLabel();
        labTelefone = new javax.swing.JLabel();
        labDataNasc = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JLabel();
        separadorV = new javax.swing.JSeparator();
        consultarEmprestimosMultas = new javax.swing.JButton();
        fecharConsulta = new javax.swing.JButton();
        separadorHSup = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        labRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labRG.setText("RG");

        labEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labEndereco.setText("Endereço");

        labNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labNome.setText("Nome Completo");
        labNome.setName(""); // NOI18N

        labCEP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labCEP.setText("CEP");

        labUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labUF.setText("Estado ou UF");

        labCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labCidade.setText("Cidade");

        labLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labLogin.setText("Login");

        labEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labEmail.setText("Email");

        nome.setBackground(new java.awt.Color(0, 153, 204));
        nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        RG.setBackground(new java.awt.Color(0, 153, 204));
        RG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        endereco.setBackground(new java.awt.Color(0, 153, 204));
        endereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CEP.setBackground(new java.awt.Color(0, 153, 204));
        CEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labCons.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labCons.setText("Consulta de Dados");

        cidade.setBackground(new java.awt.Color(0, 153, 204));
        cidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        UF.setBackground(new java.awt.Color(0, 153, 204));
        UF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        login.setBackground(new java.awt.Color(0, 153, 204));
        login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        email.setBackground(new java.awt.Color(0, 153, 204));
        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTelefone.setText("Telefone");

        labDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labDataNasc.setText("Data de Nascimento");

        dataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        separadorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        consultarEmprestimosMultas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        consultarEmprestimosMultas.setText("<html><center>Empréstimos<br>e<br>Multas</center></html>");

        fecharConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecharConsulta.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorHInf)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labUF)
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labTelefone)
                                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labNome))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(labDataNasc)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labRG)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(RG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labEndereco)
                                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labCEP)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labLogin)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                                .addComponent(login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(separadorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(251, 251, 251)
                                        .addComponent(labCons))
                                    .addComponent(labEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(fecharConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consultarEmprestimosMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addComponent(separadorHSup, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consultarEmprestimosMultas, fecharConsulta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCons)
                .addGap(1, 1, 1)
                .addComponent(separadorHSup, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(labRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCEP)
                    .addComponent(labEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labUF)
                    .addComponent(labCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTelefone)
                    .addComponent(labDataNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorHInf, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(consultarEmprestimosMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labEmail)
                                .addGap(0, 0, 0)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fecharConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(separadorV))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CEP, RG, UF, cidade, dataNascimento, email, endereco, labCEP, labCidade, labDataNasc, labEmail, labEndereco, labLogin, labNome, labRG, labTelefone, labUF, login, nome, telefone});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void retornarJanelaAnterior() {
        this.dispose();
        this.janelaAnterior.setVisible(true);
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornarJanelaAnterior();
    }//GEN-LAST:event_formWindowClosed

    private void criarInterfaceEmprestimosMultas() {
        //this.dispose();
        //this.interfaceEmprestimosMultas.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel RG;
    private javax.swing.JLabel UF;
    private javax.swing.JLabel cidade;
    private javax.swing.JButton consultarEmprestimosMultas;
    private javax.swing.JLabel dataNascimento;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JButton fecharConsulta;
    private javax.swing.JLabel labCEP;
    private javax.swing.JLabel labCidade;
    private javax.swing.JLabel labCons;
    private javax.swing.JLabel labDataNasc;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labEndereco;
    private javax.swing.JLabel labLogin;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labRG;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JLabel labUF;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nome;
    private javax.swing.JSeparator separadorHInf;
    private javax.swing.JSeparator separadorHSup;
    private javax.swing.JSeparator separadorV;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
