/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.ADM;
import Classes.Livro;
import DAO.LivroDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ryuic
 */
public class EditarAcervo extends javax.swing.JFrame {

    private ADM adm;
    private final Color corFoco = new Color(0, 0, 0);
    private final Color corInicial = new Color(204, 204, 204);
    private Livro livro;
    
    public EditarAcervo(ADM a) {
        initComponents();
        this.adm = a;
    }

    private EditarAcervo() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBusca = new javax.swing.JPanel();
        buscarLivro = new javax.swing.JButton();
        campoID = new javax.swing.JFormattedTextField();
        livroAnterior = new javax.swing.JButton();
        proximoLivro = new javax.swing.JButton();
        selecionar = new javax.swing.JButton();
        separadorV = new javax.swing.JSeparator();
        labID = new javax.swing.JLabel();
        removerLivro = new javax.swing.JButton();
        adicionarLivro = new javax.swing.JButton();
        painelLivro = new javax.swing.JPanel();
        labNome = new javax.swing.JLabel();
        labAutoria = new javax.swing.JLabel();
        labEditora = new javax.swing.JLabel();
        labAno = new javax.swing.JLabel();
        labVolume = new javax.swing.JLabel();
        labEdicao = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoAutoria = new javax.swing.JTextField();
        campoEditora = new javax.swing.JTextField();
        campoEdicao = new javax.swing.JTextField();
        campoVolume = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        imagem = new javax.swing.JPanel();
        labQuantidade = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        labAcervo = new javax.swing.JLabel();
        separadorHInf = new javax.swing.JSeparator();
        separadorHSup = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buscarLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarLivro.setText("<html><center>Buscar<br>Livro</center></html>");
        buscarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLivroActionPerformed(evt);
            }
        });

        campoID.setForeground(new java.awt.Color(204, 204, 204));
        campoID.setText("ID do Livro");
        campoID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoIDFocusLost(evt);
            }
        });
        campoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIDKeyTyped(evt);
            }
        });

        livroAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        livroAnterior.setText("<html><center>◄◄</center></html>");
        livroAnterior.setEnabled(false);

        proximoLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        proximoLivro.setText("<html><center>►►</center></html>");
        proximoLivro.setEnabled(false);

        selecionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selecionar.setText("<html><center>Editar<br>Livro</center></html>");
        selecionar.setEnabled(false);
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        separadorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labID.setText("ID");

        removerLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removerLivro.setText("<html><center>Remover<br>Livro</center></html>");
        removerLivro.setEnabled(false);
        removerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerLivroActionPerformed(evt);
            }
        });

        adicionarLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adicionarLivro.setText("<html><center>Adicionar<br>Livro</center></html>");
        adicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBuscaLayout = new javax.swing.GroupLayout(painelBusca);
        painelBusca.setLayout(painelBuscaLayout);
        painelBuscaLayout.setHorizontalGroup(
            painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBuscaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBuscaLayout.createSequentialGroup()
                        .addComponent(livroAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proximoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelBuscaLayout.createSequentialGroup()
                        .addComponent(labID)
                        .addGap(18, 18, 18)
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(separadorV, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adicionarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBuscaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {livroAnterior, proximoLivro});

        painelBuscaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buscarLivro, removerLivro, selecionar});

        painelBuscaLayout.setVerticalGroup(
            painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscaLayout.createSequentialGroup()
                .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBuscaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(selecionar)
                            .addComponent(buscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelBuscaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labID)
                            .addComponent(campoID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(livroAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proximoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(separadorV)
        );

        painelBuscaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoID, labID});

        painelBuscaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buscarLivro, removerLivro, selecionar});

        labNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labNome.setText("Nome");
        labNome.setEnabled(false);

        labAutoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labAutoria.setText("Autoria");
        labAutoria.setEnabled(false);

        labEditora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labEditora.setText("Editora");
        labEditora.setEnabled(false);

        labAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labAno.setText("Ano");
        labAno.setEnabled(false);

        labVolume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labVolume.setText("Volume");
        labVolume.setEnabled(false);

        labEdicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labEdicao.setText("Edição");
        labEdicao.setEnabled(false);

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNome.setEnabled(false);

        campoAutoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoAutoria.setEnabled(false);

        campoEditora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoEditora.setEnabled(false);

        campoEdicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoEdicao.setEnabled(false);

        campoVolume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVolume.setEnabled(false);

        campoAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoAno.setEnabled(false);

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.setEnabled(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        imagem.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout imagemLayout = new javax.swing.GroupLayout(imagem);
        imagem.setLayout(imagemLayout);
        imagemLayout.setHorizontalGroup(
            imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        imagemLayout.setVerticalGroup(
            imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        labQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labQuantidade.setText("Quantidade");
        labQuantidade.setEnabled(false);

        campoQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoQuantidade.setEnabled(false);

        javax.swing.GroupLayout painelLivroLayout = new javax.swing.GroupLayout(painelLivro);
        painelLivro.setLayout(painelLivroLayout);
        painelLivroLayout.setHorizontalGroup(
            painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLivroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelLivroLayout.createSequentialGroup()
                        .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEditora)
                            .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labAutoria)
                                .addComponent(labNome)
                                .addComponent(campoNome)
                                .addComponent(campoAutoria)
                                .addComponent(campoEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelLivroLayout.createSequentialGroup()
                        .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelLivroLayout.createSequentialGroup()
                                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLivroLayout.createSequentialGroup()
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labEdicao)
                                    .addComponent(campoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labVolume)
                                    .addComponent(campoVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labAno)
                                    .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labQuantidade)
                                    .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)))
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelLivroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelar, confirmar});

        painelLivroLayout.setVerticalGroup(
            painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLivroLayout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labAutoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAutoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLivroLayout.createSequentialGroup()
                                .addComponent(labEditora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labEdicao)
                                    .addComponent(labVolume)
                                    .addComponent(labAno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLivroLayout.createSequentialGroup()
                                .addComponent(labQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLivroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(painelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        painelLivroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoAno, campoAutoria, campoEdicao, campoEditora, campoNome, campoVolume, labAno, labAutoria, labEdicao, labEditora, labNome, labVolume});

        painelLivroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelar, confirmar});

        labAcervo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labAcervo.setText("Editar Acervo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(labAcervo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(separadorHInf, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(separadorHSup)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labAcervo)
                .addGap(5, 5, 5)
                .addComponent(separadorHSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorHInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 736, 513);
    }// </editor-fold>//GEN-END:initComponents
    
    private int ID;
    private String nome;
    private short volume;
    private short edicao;
    private String autoria;
    private String editora;
    private short ano;
    private short quantidade;
    
    private void retornarJanelaAnterior() {
        this.dispose();
        this.adm.mostraInterface(this.getX(), this.getY());
    }
    
    private void carregaCampos() {
        campoNome.setText(livro.getNome());
        campoVolume.setText(String.valueOf(livro.getVolume()));
        campoEdicao.setText(String.valueOf(livro.getEdicao()));
        campoAutoria.setText(livro.getAutoria());
        campoEditora.setText(livro.getEditora());
        campoAno.setText(String.valueOf(livro.getAno()));
        campoQuantidade.setText(String.valueOf(livro.getQuantidade()));
    }
    
    private void habilitaEdicaoLivro() {
        LivroDAO livroDAO = new LivroDAO();
        
        ID = Integer.parseInt(this.campoID.getText());
        
        livro = livroDAO.buscarLivroID(ID);
        
        if(livro != null) {
            habilitaCampos();
            carregaCampos();
            this.removerLivro.setEnabled(true);
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Erro de Conexão");
        }
    }
    
    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        habilitaEdicaoLivro();
    }//GEN-LAST:event_selecionarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        retornarJanelaAnterior();
    }//GEN-LAST:event_cancelarActionPerformed
    
    private void campoFocoGanho(JTextComponent campo) {
        if(campo.getForeground().equals(this.corInicial)) {
            campo.setCaretPosition(0);
            campo.setForeground(corFoco);
            campo.setText("");
        }
    }
    
    private void campoIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIDFocusGained
        JTextComponent campo = (JTextComponent)evt.getComponent();
        campoFocoGanho(campo);
    }//GEN-LAST:event_campoIDFocusGained
    
    private void campoFocoPerdido(JTextComponent campo) {
        if(campo.getText().equals("")) {
            campo.setText("ID do Livro");
            campo.setForeground(corInicial);
        }
    }
    
    private void campoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIDFocusLost
        JTextComponent campo = (JTextComponent)evt.getComponent();
        campoFocoPerdido(campo);
    }//GEN-LAST:event_campoIDFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retornarJanelaAnterior();
    }//GEN-LAST:event_formWindowClosing
    
    private void resetaCampos() {
        this.campoNome.setText("");
        this.campoVolume.setText("");
        this.campoEdicao.setText("");
        this.campoAutoria.setText("");
        this.campoEditora.setText("");
        this.campoAno.setText("");
        this.campoQuantidade.setText("");
    }
    
    private void desabilitaCampos() {
        int i;
        Component componente;
                
        for(i = 0; i < this.painelLivro.getComponentCount(); i++) {
            componente = this.painelLivro.getComponent(i);
            componente.setEnabled(false);
        }
        
        this.cancelar.setEnabled(true);
    }
    
    private void habilitaCampos() {
        int i;
        Component componente;
                
        for(i = 0; i < this.painelLivro.getComponentCount(); i++) {
            componente = this.painelLivro.getComponent(i);
            componente.setEnabled(true);
        }
    }
    
    private void habilitaAdicaoLivro() {
        habilitaCampos();
        
        this.confirmar.setEnabled(true);
        this.adicionarLivro.setEnabled(false);
    }
    
    private void adicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarLivroActionPerformed
        habilitaAdicaoLivro();
    }//GEN-LAST:event_adicionarLivroActionPerformed
    
    private void defineAtributos() {
        nome = this.campoNome.getText();
        volume = Short.parseShort(this.campoVolume.getText());
        edicao = Short.parseShort(this.campoEdicao.getText());
        autoria = this.campoAutoria.getText();
        editora = this.campoEditora.getText();
        ano = Short.parseShort(this.campoAno.getText());
        quantidade = Short.parseShort(this.campoQuantidade.getText());
    }
    
    private void adicionaLivro() {
        LivroDAO livroDAO = new LivroDAO();
        
        ID = livroDAO.encontraIDVazio();
        
        defineAtributos();
        
        livro = new Livro(ID, nome, volume, edicao, autoria, editora, ano, quantidade);
        
        livroDAO = new LivroDAO();
        
        if(livroDAO.salvar(livro)) {
            JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
            
            resetaCampos();
            desabilitaCampos();
            
            this.confirmar.setEnabled(false);
            this.adicionarLivro.setEnabled(true);
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Erro de Conexão");
        }
    }
    
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        adicionaLivro();
    }//GEN-LAST:event_confirmarActionPerformed

    private void buscarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarLivroActionPerformed
    
    private void verificaTecla(KeyEvent evt) {
        char tecla = evt.getKeyChar();
        
        if(this.campoID.getText().equals("")) {
            this.selecionar.setEnabled(false);
        }
        
        if(tecla > 47 && tecla < 58) {
            selecionar.setEnabled(true);
        }
        
        else {
            evt.consume();
        }
    }
    
    private void campoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIDKeyTyped
        verificaTecla(evt);
    }//GEN-LAST:event_campoIDKeyTyped
    
    private void teclaPressionada(KeyEvent evt) {
        int codigoTecla = evt.getKeyCode();
        
        if(this.campoID.getText().equals("")) {
            this.selecionar.setEnabled(false);
        }
        
        if(codigoTecla != 8 && codigoTecla != 127) {
            evt.consume();
        }
    }
    
    private void campoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIDKeyPressed
        teclaPressionada(evt);
    }//GEN-LAST:event_campoIDKeyPressed
    
    private void removeLivro() {
        LivroDAO usuarioDAO = new LivroDAO();
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente deletar este livro?");
        
        if(opcao == 0) {
            usuarioDAO.deletar(livro);
            desabilitaCampos();
            resetaCampos();
        }
    }
    
    private void removerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerLivroActionPerformed
        removeLivro();
    }//GEN-LAST:event_removerLivroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarLivro;
    private javax.swing.JButton buscarLivro;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoAutoria;
    private javax.swing.JTextField campoEdicao;
    private javax.swing.JTextField campoEditora;
    private javax.swing.JFormattedTextField campoID;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JTextField campoVolume;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JPanel imagem;
    private javax.swing.JLabel labAcervo;
    private javax.swing.JLabel labAno;
    private javax.swing.JLabel labAutoria;
    private javax.swing.JLabel labEdicao;
    private javax.swing.JLabel labEditora;
    private javax.swing.JLabel labID;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labQuantidade;
    private javax.swing.JLabel labVolume;
    private javax.swing.JButton livroAnterior;
    private javax.swing.JPanel painelBusca;
    private javax.swing.JPanel painelLivro;
    private javax.swing.JButton proximoLivro;
    private javax.swing.JButton removerLivro;
    private javax.swing.JButton selecionar;
    private javax.swing.JSeparator separadorHInf;
    private javax.swing.JSeparator separadorHSup;
    private javax.swing.JSeparator separadorV;
    // End of variables declaration//GEN-END:variables
}
