/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.ADM;

/**
 *
 * @author Gabriel
 */
public class InterfaceAdm extends javax.swing.JFrame {

    private ADM adm;
    private final String msgBoasVindas = "Bem-Vindo, ";
    
    private InterfaceAdm() {
        
    }

    public InterfaceAdm(ADM a) {
        initComponents();
        this.adm = a;
        this.labAdm.setText(this.msgBoasVindas + a.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAcervo = new javax.swing.JPanel();
        labAcervo = new javax.swing.JLabel();
        consultarAcervo = new javax.swing.JButton();
        editarAcervo = new javax.swing.JButton();
        painelUsuarios = new javax.swing.JPanel();
        labUsuarios = new javax.swing.JLabel();
        cadastrarUsuario = new javax.swing.JButton();
        alterarUsuario = new javax.swing.JButton();
        emprestarLivro = new javax.swing.JButton();
        separadorV = new javax.swing.JSeparator();
        separadorH = new javax.swing.JSeparator();
        labAdm = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        consultarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(720, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painelAcervo.setBackground(new java.awt.Color(204, 255, 204));

        labAcervo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labAcervo.setText("Acervo");

        consultarAcervo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        consultarAcervo.setText("Consultar");
        consultarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAcervoActionPerformed(evt);
            }
        });

        editarAcervo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editarAcervo.setText("Editar");
        editarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAcervoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAcervoLayout = new javax.swing.GroupLayout(painelAcervo);
        painelAcervo.setLayout(painelAcervoLayout);
        painelAcervoLayout.setHorizontalGroup(
            painelAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcervoLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(labAcervo)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(painelAcervoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(consultarAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(editarAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );

        painelAcervoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consultarAcervo, editarAcervo});

        painelAcervoLayout.setVerticalGroup(
            painelAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labAcervo)
                .addGap(20, 20, 20)
                .addComponent(consultarAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(editarAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        painelAcervoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {consultarAcervo, editarAcervo});

        painelUsuarios.setBackground(new java.awt.Color(255, 255, 204));

        labUsuarios.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labUsuarios.setText("Usuários");

        cadastrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cadastrarUsuario.setText("Cadastrar");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });

        alterarUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alterarUsuario.setText("<html>Alterar<br>Dados</html>");
        alterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUsuarioActionPerformed(evt);
            }
        });

        emprestarLivro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emprestarLivro.setText("Empréstimo");
        emprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelUsuariosLayout = new javax.swing.GroupLayout(painelUsuarios);
        painelUsuarios.setLayout(painelUsuariosLayout);
        painelUsuariosLayout.setHorizontalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUsuariosLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labUsuarios)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelUsuariosLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emprestarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alterarUsuario, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(66, 66, 66))
        );

        painelUsuariosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alterarUsuario, cadastrarUsuario});

        painelUsuariosLayout.setVerticalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labUsuarios)
                .addGap(20, 20, 20)
                .addComponent(cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emprestarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        separadorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labAdm.setBackground(new java.awt.Color(204, 204, 255));
        labAdm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labAdm.setOpaque(true);

        logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        consultarDados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        consultarDados.setText("<html><center>Dados<br>Pessoais</center></html>");
        consultarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorH)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(separadorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consultarDados, logout});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {painelAcervo, painelUsuarios});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarDados)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorH, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(separadorV)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {consultarDados, logout});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {painelAcervo, painelUsuarios});

        setBounds(0, 0, 736, 519);
    }// </editor-fold>//GEN-END:initComponents
    
    private void criarInterfaceConsultarAcervo() {
        this.dispose();
        this.adm.consultaAcervo();
    }
    
    private void consultarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAcervoActionPerformed
        criarInterfaceConsultarAcervo();
    }//GEN-LAST:event_consultarAcervoActionPerformed
    
    private void criarInterfaceEditarAcervo() {
        this.dispose();
        this.adm.editaAcervo();
    }
    
    private void editarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAcervoActionPerformed
        criarInterfaceEditarAcervo();
    }//GEN-LAST:event_editarAcervoActionPerformed
    
    private void criarInterfaceCadastrarUsuario() {
        this.dispose();
        this.adm.cadastraUsuario();
    }
    
    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        criarInterfaceCadastrarUsuario();
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed
    
    private void criarInterfaceAlterarUsuario() {
        this.dispose();
        this.adm.editaUsuario();
    }
    
    private void alterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUsuarioActionPerformed
        criarInterfaceAlterarUsuario();
    }//GEN-LAST:event_alterarUsuarioActionPerformed
    
    private void retornarJanelaAnterior() {
        this.dispose();
        
        InterfaceBiblioteca biblioteca = new InterfaceBiblioteca();
        biblioteca.setLocation(this.getLocation());
        biblioteca.setVisible(true);
    }
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        retornarJanelaAnterior();
    }//GEN-LAST:event_logoutActionPerformed
    
    private void criarInterfaceConsultarDados() {
        this.dispose();
        this.adm.consultaDados();
    }
    
    private void consultarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDadosActionPerformed
        criarInterfaceConsultarDados();
    }//GEN-LAST:event_consultarDadosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retornarJanelaAnterior();
    }//GEN-LAST:event_formWindowClosing
    
    private void criarInterfaceEmprestimoAdm() {
        InterfaceEmprestimoAdm intEmpAdm = new InterfaceEmprestimoAdm(this, true);
        intEmpAdm.setLocation(this.getX() + this.getWidth()/2 - intEmpAdm.getWidth()/2, this.getY() + this.getHeight()/2 - intEmpAdm.getHeight()/2);
        intEmpAdm.setVisible(true);
    }
    
    private void emprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarLivroActionPerformed
        criarInterfaceEmprestimoAdm();
    }//GEN-LAST:event_emprestarLivroActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarUsuario;
    private javax.swing.JButton cadastrarUsuario;
    private javax.swing.JButton consultarAcervo;
    private javax.swing.JButton consultarDados;
    private javax.swing.JButton editarAcervo;
    private javax.swing.JButton emprestarLivro;
    private javax.swing.JLabel labAcervo;
    private javax.swing.JLabel labAdm;
    private javax.swing.JLabel labUsuarios;
    private javax.swing.JButton logout;
    private javax.swing.JPanel painelAcervo;
    private javax.swing.JPanel painelUsuarios;
    private javax.swing.JSeparator separadorH;
    private javax.swing.JSeparator separadorV;
    // End of variables declaration//GEN-END:variables
}
