/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.LivroDAO;
import DAO.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ryuic
 */
public class InterfaceEmprestimoAdm extends javax.swing.JDialog {
    
    private final Color corValido = new Color(50, 120, 80);
    private final Color corInvalido = new Color(120, 80, 50);
    private final boolean idsValidos[] = new boolean[2];
    
    /**
     * Creates new form InterfaceEmprestimo
     * @param parent
     * @param modal
     */
    public InterfaceEmprestimoAdm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labEmprestimo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        emprestarLivro = new javax.swing.JButton();
        devolverLivro = new javax.swing.JButton();
        labIDLivro = new javax.swing.JLabel();
        labIDUsuario = new javax.swing.JLabel();
        campoIDUsuario = new javax.swing.JFormattedTextField();
        campoIDLivro = new javax.swing.JFormattedTextField();
        fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labEmprestimo.setText("Empréstimo");

        emprestarLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emprestarLivro.setText("Emprestar");
        emprestarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestarLivroActionPerformed(evt);
            }
        });

        devolverLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        devolverLivro.setText("Devolver");
        devolverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverLivroActionPerformed(evt);
            }
        });

        labIDLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIDLivro.setText("ID Livro");

        labIDUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIDUsuario.setText("ID Usuário");

        campoIDUsuario.setText("_____");
        campoIDUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        campoIDLivro.setText("_____");
        campoIDLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fechar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labIDUsuario)
                    .addComponent(campoIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labIDLivro)
                    .addComponent(campoIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devolverLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emprestarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(labEmprestimo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(labEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emprestarLivro)
                        .addGap(18, 18, 18)
                        .addComponent(devolverLivro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labIDUsuario)
                            .addComponent(labIDLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(fechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed
    
    private void verificaIdUsuario(int idUsuario) {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        
        if(usuarioDAO.procurarUsuario(idUsuario) != null) {
            this.labIDUsuario.setForeground(corValido);
            this.idsValidos[0] = true;
        }
        
        else {
            this.labIDUsuario.setForeground(corInvalido);
            this.idsValidos[0] = false;
        }
    }
    
    private void verificaIdLivro(int idLivro) {
        LivroDAO livroDAO = new LivroDAO();
        
        if(livroDAO.buscarLivroID(idLivro) != null) {
            this.labIDLivro.setForeground(corValido);
            this.idsValidos[1] = true;
        }
        
        else {
            this.labIDLivro.setForeground(corInvalido);
            this.idsValidos[1] = false;
        }
    }
    
    private void emprestaLivro() {
        int idUsuario = Integer.parseInt(this.campoIDUsuario.getText());
        int idLivro = Integer.parseInt(this.campoIDLivro.getText());
        
        verificaIdUsuario(idUsuario);
        verificaIdLivro(idLivro);
        
        if(idsValidos[0] == true && idsValidos[1] == true) {
            LivroDAO livroDAO = new LivroDAO();
            
            if(livroDAO.emprestar(idUsuario, idLivro)) {
                JOptionPane.showMessageDialog(this, "Livro emprestado com sucesso!");
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Erro ao emprestar livro!");
            }
        }
    }
    
    private void emprestarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarLivroActionPerformed
        emprestaLivro();
    }//GEN-LAST:event_emprestarLivroActionPerformed
    
    private void devolveLivro() {
        int idUsuario = Integer.parseInt(this.campoIDUsuario.getText());
        int idLivro = Integer.parseInt(this.campoIDLivro.getText());
        
        verificaIdUsuario(idUsuario);
        verificaIdLivro(idLivro);
        
        if(idsValidos[0] == true && idsValidos[1] == true) {
            LivroDAO livroDAO = new LivroDAO();
            
            if(livroDAO.devolver(idUsuario, idLivro)) {
                JOptionPane.showMessageDialog(this, "Livro devolvido com sucesso!");
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Erro ao devolver livro!");
            }
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Erro ao devolver livro!");
        }
    }
    
    private void devolverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverLivroActionPerformed
        devolveLivro();
    }//GEN-LAST:event_devolverLivroActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoIDLivro;
    private javax.swing.JFormattedTextField campoIDUsuario;
    private javax.swing.JButton devolverLivro;
    private javax.swing.JButton emprestarLivro;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel labEmprestimo;
    private javax.swing.JLabel labIDLivro;
    private javax.swing.JLabel labIDUsuario;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
