/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author ryuic
 */
public class InterfaceMulta extends javax.swing.JDialog {

    /**
     * Creates new form InterfaceMulta
     * @param parent
     * @param modal
     * @param multa
     */
    public InterfaceMulta(java.awt.Frame parent, boolean modal, String multa) {
        super(parent, modal);
        initComponents();
        
        this.rotuloValorMulta.setText("R$" + multa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labMulta = new javax.swing.JLabel();
        labValor = new javax.swing.JLabel();
        rotuloValorMulta = new javax.swing.JLabel();
        realizarPagamento = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labMulta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labMulta.setText("Multa");

        labValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labValor.setText("Valor:");

        rotuloValorMulta.setBackground(new java.awt.Color(204, 204, 255));
        rotuloValorMulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotuloValorMulta.setOpaque(true);

        realizarPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        realizarPagamento.setText("Pagar");
        realizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPagamentoActionPerformed(evt);
            }
        });

        fechar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotuloValorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(labMulta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(separador)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(realizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labMulta)
                .addGap(10, 10, 10)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotuloValorMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechar)
                    .addComponent(realizarPagamento))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarPagamentoActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fechar;
    private javax.swing.JLabel labMulta;
    private javax.swing.JLabel labValor;
    private javax.swing.JButton realizarPagamento;
    private javax.swing.JLabel rotuloValorMulta;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
